### ISSUE TITLE
Crashes with this on a video file...

### ISSUE THREAD

**Issue by thpryrchn** [zeroepoch/plotbitrate#1]
Traceback (most recent call last):
  File "/private/tmp/plotbitrate-master/plotbitrate.py", line 157, in <module>
    frame_time = float(node.get('pkt_pts_time'))
TypeError: float() argument must be a string or a number

Using Python 3.3 on a mac. Installed with macports 'port install python33 py33-matplotlib'
also had to edit the first line to '#!/usr/bin/env python3.3' to get it to run.

**Comment by zeroepoch** [comment]
Does this happen for all video files you tried or just a certain video file?

**Comment by zeroepoch** [comment]
This may be because you have a version of ffmpeg/ffprobe that doesn't provide the `pkt_pts_time` field.  Without this field you won't have a value for the x-axis.  What version of ffmpeg do you have installed?  For further debug you could try adding the following line right before frame_time is defined (between 156 and 157):

```
print(node.get('pkt_pts_time'))
```

**Comment by zeroepoch** [comment]
Closing out old issues
