### ISSUE TITLE
Is it possible to change moving average window length?

### ISSUE THREAD

**Issue by bahadirbasaran** [zeroepoch/plotbitrate#17]
Hello!

Thank you for this useful tool.

In order to use it in my project, I need to try different moving average window lengths while generating bitrate/time graphs from my frames. Is it possible to do this in plotbitrate, or do I need to use plain ffmpeg for this purpose?

Cheers!

**Comment by zeroepoch** [comment]
There isn't an easy way to do this at the moment since the bitrate algorithm only combines data that is part of the same second. There is an option to output the raw data in CSV or XML format and then you could process as needed in Excel or another plotting tool. That should at least save you some hassle from dealing with ffmpeg directly and you can benefit from the multi-threading.

**Comment by bahadirbasaran** [comment]
Thank you for the answer @zeroepoch
May I ask you to make the bitrate algorithm more clear? You have said that the algorithm "combines" data that is part of the same second. Does it directly averages frame sizes that belong to the same second, or does it having moving averages? Considering the function "frames_to_kbits", I guess it only averages the sizes between the seconds [n, n+1]. Am I right about this?
Cheers!

**Comment by rezun** [comment]
Hey @bahadirbasaran 
To clear things up, the algorithm does not contain any type of averaging of values.
It's simply the sum of frame sizes grouped by second.
It would be possible to implement some moving average by replacing/extending the frames_to_kbits function but currently there's no such thing planned.

**Comment by bahadirbasaran** [comment]
Thank you for the clarification @rezun . I am closing this issue.
