### ISSUE TITLE
Size mismatch between sum of "pkt_size" values and size in XML output

### ISSUE THREAD

**Issue by bahadirbasaran** [zeroepoch/plotbitrate#18]
Hello!
I am not sure whether this is a bug, maybe there is a point that I am not realized of. I generated the following XML file according to my video input.

![ss](https://user-images.githubusercontent.com/48394310/104853184-7c491080-58ff-11eb-9037-b8f2ab5cf0dc.png)

In the format tag, it shows the total size as 207124356 Bytes. However, my script calculates the sum of all "pkt_size" values as 207070641 Bytes. Can I ask you the reason for this difference? Am I missing something?
Thanks!

**Comment by rezun** [comment]
This xml file is generated by ffmpeg with the ffprobe command.
The format element contains general information about the file.
So, the size value in the format element represents the size of the whole file, including all streams (video, audio) and metadata.
Since the frame elements only contain video frame information of one video stream, the sum of pkt_size will be the size of the particular stream only (headers excluded).
<img width="653" alt="sizes" src="https://user-images.githubusercontent.com/1188549/104913809-777f6d80-598e-11eb-9781-e8b691a5fd5b.png">
